### PR TITLE
Support older Rust versions

### PR DESCRIPTION
**Pull request by djc**

### CODE REVIEW

**Comment by djc** [comment]
(Also, Travis is pretty crappy these days. Would you like me to do a PR with an equivalent GitHub Actions config?)

**Comment by steveklabnik** [comment]
Thanks for this!

> (Also, Travis is pretty crappy these days. Would you like me to do a PR with an equivalent GitHub Actions config?)

I am not planning on developing this further, and am putting my efforts into the re-write, so if you'd like to, feel free, but that's why it hasn't been a priority for me.

**Comment by djc** [comment]
Okay, I'll just leave it then. So does it make sense to just merge and release this?

Out of curiosity, which rewrite are you referring to? Is that public somewhere?

**Comment by steveklabnik** [comment]
> Okay, I'll just leave it then. So does it make sense to just merge and release this?

Yes. Might take me a day or two.

> Out of curiosity, which rewrite are you referring to? Is that public somewhere?

I've been working on getting semver to 1.0 for a while now, and when doing so, I realized that I don't like the API of either of these crates very much. So I've been working on a re-implementation. Actually, several, technically. With the state of the world right now, it's been very very hard to find the time to finish it off. So I'm still doing some degree of maintenance on these crates in the meantime.

The end result is something that is much simpler API wise, but ends up supporting more features, and works with `no_std`. I'll get there.

**Comment by djc** [comment]
> Yes. Might take me a day or two.

Great, thanks.

> I'll get there.

Would you like some help? I could provide some code reviews and/or help write some code if you type up a little roadmap. I ran into some limitations while working on a cargo feature and am using semver in a few other projects I maintain.

**Comment by djc** [comment]
Hi Steve, friendly reminder -- hope this is still on your radar?

**Comment by steveklabnik** [comment]
It is, yes, sorry. Will cut a release tomorrow morning.

**Comment by kjeremy** [comment]
It looks like `cargo_metadata` has this package pinned to `0.10.0` to keep an MSRV of 1.32: https://github.com/oli-obk/cargo_metadata/pull/142#issuecomment-733009864

**Comment by djc** [comment]
@steveklabnik friendly ping for the new year? It should be a quick review, I promise!

(Also, offer to co-maintain still stands -- might help you focus on the new implementation.)

**Review by steveklabnik — APPROVED** [review]

**Comment by steveklabnik** [comment]
Hi. Hi. So sorry again. I have... not had a good time lately, to be honest.

I have published 0.10.2 with this fix in it. So sorry again.

**Comment by djc** [comment]
I'm so sorry to hear that! If you need someone talk to, I'd be happy to listen if that helps.

**Pull request merged**
